Repository metomi/rose, pull requests merged in 2019-06, with the labels that each got.

#2350 docs: sphinx 2.1.0 compatability
  sphinx/ext/rose_domain.py
Labels: bug, doc

#2346 mojibake fix [Sphinx Fail == Master Sphinx Fail]
  ACKNOWLEDGEMENT.md
  lib/python/rose/tests/test_ancils/unicode.txt
  lib/python/rose/tests/test_env.py
  lib/python/rose/tests/test_popen.py
  lib/python/rose/tests/test_unicode_handling.py
Labels: bug

#2348 2019.01.x docs: fix what-is-cylc page
  sphinx/hyperlinks.rst
  sphinx/tutorial/cylc/introduction.rst
Labels: doc

#2353 config.load: permit unicode filename
  lib/python/rose/config.py
Labels: bug

#2352 [2019.01.x] Fix Travis CI build
  .travis.yml
  t/rose-app-run/06-namelist.t
Labels: bug

#2347 docs: fix what-is-cylc page
  sphinx/tutorial/cylc/introduction.rst
Labels: doc

#2349 doc: simplify cylc graphing tutorial
  sphinx/_static/css/metomi.css
  sphinx/tutorial/cylc/scheduling/graphing.rst
Labels: doc

#2356 travis: restore coverage
  .travis/now
Labels: bug

#2336 [7.x] cylc tutorial: don't depend on PYTHONPATH being defined
  etc/tutorial/consolidation-tutorial/suite.rc
  etc/tutorial/cylc-forecasting-suite/suite.rc
  etc/tutorial/rose-weather-forecasting-suite/suite.rc
  etc/tutorial/runtime-tutorial/runtime
  sphinx/tutorial/cylc/runtime/configuration-consolidation/families.rst
  sphinx/tutorial/rose/suites.rst
Labels: doc

#2351 docs: tutorial tweaks
  sphinx/course/um-ut.rst
  sphinx/index.rst
  sphinx/tutorial/cylc/scheduling/datetime-cycling.rst
  sphinx/tutorial/cylc/scheduling/integer-cycling.rst
  sphinx/tutorial/rose/metadata.rst
  sphinx/tutorial/rose/suites.rst
Labels: doc
