Repository metomi/rose, pull requests merged in 2019-10, with the labels that each got.

#2380 rose suite-run: fix bytecode issue with shell-containing cylc remote host settings
  metomi/rose/suite_engine_procs/cylc.py
  t/rose-suite-run/02-install.t
  t/rose-suite-run/02-install/app/my_task_2/rose-app.conf
  t/rose-suite-run/02-install/suite.rc
  t/rose-suite-run/29-install-host-localhost
  t/rose-suite-run/29-install-host-localhost.t
Labels: bug

#2383 fix rose-arch docs
  metomi/rose/apps/rose_arch.py
  sphinx/_static/custom.css
  sphinx/api/built-in/rose_arch.rst
  sphinx/conf.py
Labels: doc

#2381 Changed unittest to pytest. Added name to contributing.
  CONTRIBUTING.md
  metomi/rose/tests/test_config.py
Labels: testing
