Repository metomi/rose, pull requests merged in 2021-12, with the labels that each got.

#2512 fixed SRS hyperlink
  sphinx/hyperlinks.rst
  sphinx/tutorial/rose/rosie.rst
Labels: small

#2498 actions: enable macos testing
  .github/workflows/test.yml
  metomi/rose/scripts/rosa-rpmbuild
Labels: small

#2509 Popen always decodes
  metomi/rose/apps/ana_builtin/grepper.py
  metomi/rose/apps/rose_arch.py
  metomi/rose/apps/rose_prune.py
  metomi/rose/check_software.py
  metomi/rose/config_diff.py
  metomi/rose/host_select.py
  metomi/rose/loc_handlers/rsync.py
  metomi/rose/popen.py
  metomi/rose/suite_engine_procs/cylc.py
  metomi/rosie/suite_id.py
  metomi/rosie/svn_hook.py
  metomi/rosie/vc.py
  sphinx/api/command-reference.rst
Labels: small

#2515 fixed broken link.
  sphinx/hyperlinks.rst
Labels: doc, small

#2516 added nitpicky mode to sphinx options
  sphinx/Makefile
Labels: doc, small

#2520 Update `rosie id` to use new JSON format for Cylc VCS logs
  metomi/rosie/suite_id.py
  metomi/rosie/tests/test_suite_id.py
  pytest.ini
Labels: rosie, small

#2529 Remove files accidentally duplicated when converting Rose to a package.
  metomi/rose/etc/fcm_make/HEAD/rose-meta.conf
  metomi/rose/etc/rose-all/etc/images/icon.png
  metomi/rose/etc/rose-all/rose-meta.conf
  metomi/rose/etc/rose-app-conf/rose-meta.conf
  metomi/rose/etc/rose-demo-baked-alaska-icecream/HEAD/rose-meta.conf
  metomi/rose/etc/rose-demo-baked-alaska-icecream/vn1.0/rose-meta.conf
  metomi/rose/etc/rose-demo-baked-alaska-icecream/vn2.0/rose-meta.conf
  metomi/rose/etc/rose-demo-baked-alaska-sponge/HEAD/rose-meta.conf
  metomi/rose/etc/rose-demo-baked-alaska-sponge/vn1.0/lib/python/macros/__init__.py
  metomi/rose/etc/rose-demo-baked-alaska-sponge/vn1.0/lib/python/macros/desoggy.py
  metomi/rose/etc/rose-demo-baked-alaska-sponge/vn1.0/rose-meta.conf
  metomi/rose/etc/rose-demo-baked-alaska-sponge/vn2.0/rose-meta.conf
  metomi/rose/etc/rose-demo-baked-alaska/HEAD/rose-meta.conf
  metomi/rose/etc/rose-demo-baked-alaska/vn1.0/rose-meta.conf
  metomi/rose/etc/rose-demo-baked-alaska/vn2.0/rose-meta.conf
  metomi/rose/etc/rose-demo-upgrade-null/0.1/rose-meta.conf
  metomi/rose/etc/rose-demo-upgrade-null/0.2/rose-meta.conf
  metomi/rose/etc/rose-demo-upgrade-null/versions.py
  metomi/rose/etc/rose-demo-upgrade/HEAD/rose-meta.conf
  metomi/rose/etc/rose-demo-upgrade/etc/garden0.4/rose-macro-add.conf
  metomi/rose/etc/rose-demo-upgrade/garden0.1/rose-meta.conf
  metomi/rose/etc/rose-demo-upgrade/garden0.2/rose-meta.conf
  metomi/rose/etc/rose-demo-upgrade/garden0.3/rose-meta.conf
  metomi/rose/etc/rose-demo-upgrade/garden0.4/rose-meta.conf
  metomi/rose/etc/rose-demo-upgrade/garden0.9/rose-meta.conf
  metomi/rose/etc/rose-demo-upgrade/versions.py
  metomi/rose/etc/rose-suite-conf/rose-meta.conf
  metomi/rose/etc/rose-suite-info/rose-meta.conf
  metomi/rose/etc/rose_bunch/HEAD/rose-meta.conf
  metomi/rose/etc/rose_prune/HEAD/rose-meta.conf
Labels: bug?
