Repository metomi/rose, pull requests merged in 2022-03, with the labels that each got.

#2559 docs: pin Cylc intersphinx to cylc-doc:latest
  sphinx/conf.py
Labels: bug, doc

#2554 actions: enable mypy
  .github/workflows/test.yml
  setup.cfg
Labels: small

#2555 Invoke host-select via bash login shell
  metomi/rose/app_run.py
  metomi/rose/etc/rose-meta/rose-app-conf/rose-meta.conf
  metomi/rose/host_select.py
  metomi/rose/popen.py
  metomi/rose/run_source_vc.py
  metomi/rose/suite_engine_procs/cylc.py
  metomi/rose/tests/suite_engine_procs/test_cylc.py
  setup.cfg
  sphinx/api/configuration/application.rst
  t/rose-app-run/08-poll.t
  t/rose-host-select/00-basic.t
  t/rose-host-select/01-timeout.t
  t/rose-host-select/02-localhost.t
Labels: bug

#2562 Update changelog
  CHANGES.md
Labels: small

#2557 Fcm make fix for remote and subshell platforms
  CHANGES.md
  metomi/rose/apps/fcm_make.py
  metomi/rose/popen.py
  metomi/rose/suite_engine_procs/cylc.py
  t/rose-task-run/08-app-fcm-make.t
  t/rose-task-run/08-app-fcm-make/flow.cylc
Labels: bug

#2567 Actions: Add test badge to release PRs
  .github/workflows/1_create_release_pr.yml
Labels: small, infrastructure
