Repository metomi/rose, pull requests merged in 2022-02, with the labels that each got.

#2537 upgrade: clarify documentation
  metomi/rose/upgrade.py
Labels: doc, small

#2536 renamed function job_logs_pull_remote → job_logs_housekeep_remote
  metomi/rose/apps/rose_prune.py
  metomi/rose/suite_engine_proc.py
  metomi/rose/suite_engine_procs/cylc.py
  sphinx/api/built-in/rose_prune.rst
Labels: doc, small

#2540 pygraphviz < 1.8
  .github/workflows/test.yml
  setup.cfg
Labels: small

#2551 docs: edit release candidate message
  sphinx/index.rst
Labels: doc
