Repository metomi/rose, pull requests merged in 2024-07, with the labels that each got.

#2783 Replace "template variables" with "template_variables"
  .coveragerc
  metomi/rose/macros/rule.py
  metomi/rose/tests/macros/test_rule.py
  t/rose-metadata-check/12-template-variables.t
Labels: bug, small

#2797 GH Actions: patch DNS on MacOS
  .github/workflows/test.yml
Labels: small, infrastructure

#2801 rose_prune: improve docs
  sphinx/api/built-in/rose_prune.rst
Labels: doc

#2803 Fix Forkme banner & Add see rst source
  sphinx/conf.py
  sphinx/index.rst
Labels: small
