Repository metomi/rose, pull requests merged in 2024-10, with the labels that each got.

#2817 GH actions: update deprecated syntax
  .github/workflows/update_tutorials.yml
Labels: small, infrastructure

#2818 Fix traceback when git is not installed
  metomi/rose/loc_handlers/git.py
  metomi/rose/popen.py
  metomi/rose/tests/test_git.py
Labels: bug

#2822 update eslint environment
  tox.ini
  yarn.lock
Labels: small
