Repository metomi/rose, pull requests merged in 2025-04, with the labels that each got.

#2867 ConfigNodeDiff.get_as_opt_config: preserve parent attributes
  metomi/rose/config.py
  metomi/rose/macro.py
  t/rose-app-upgrade/14-same-transformation-applied-to-opt-config.t
  t/rose-app-upgrade/14-same-transformation-applied-to-opt-config/app/example_app/opt/rose-app-demo.conf
  t/rose-app-upgrade/14-same-transformation-applied-to-opt-config/app/example_app/rose-app.conf
  t/rose-app-upgrade/14-same-transformation-applied-to-opt-config/rose-meta/example_meta/HEAD/rose-meta.conf
  t/rose-app-upgrade/14-same-transformation-applied-to-opt-config/rose-meta/example_meta/versions.py
  t/rose-app-upgrade/14-same-transformation-applied-to-opt-config/rose-meta/example_meta/vn1.0/rose-meta.conf
Labels: bug

#2876 GH Actions: use latest `pypa/gh-action-pypi-publish`
  .github/workflows/2_auto_publish_release.yml
Labels: small, dependencies, infrastructure

#2888 Use towncrier for changelog generation
  .github/workflows/1_create_release_pr.yml
  .github/workflows/test.yml
  CHANGES.md
  CONTRIBUTING.md
  changes.d/changelog-template.jinja
  pyproject.toml
  setup.cfg
Labels: small, infrastructure
