Repository metomi/rose, pull requests merged in 2025-03, with the labels that each got.

#2863 Fix tests broken by change in Python 3.13 error messages
  .github/workflows/test.yml
  t/rose-macro/09-rule-check.t
  t/rose-metadata-check/04-pattern.t
  t/rose-metadata-check/09-custom-macro.t
  t/rose-task-run/07-app-arch.t
Labels: small

#2866 Cherry-pick #2837
  sphinx/tutorial/rose/furthertopics/command-keys.rst
  sphinx/tutorial/rose/furthertopics/polling.rst
  sphinx/tutorial/rose/furthertopics/rose-arch.rst
  sphinx/tutorial/rose/furthertopics/rose-bunch.rst
  sphinx/tutorial/rose/furthertopics/rose-stem-tutorial.rst
  sphinx/tutorial/rose/suites.rst
Labels: doc, small

#2865 actions: use mamba to provision Python environment
  .github/workflows/test.yml
  t/rose-config-diff/00-basic.t
Labels: infrastructure
